/**
 * M5-F-INT — a DB-backed stub app for the end-to-end isolation gate.
 *
 * A minimal Next app whose state lives in SQLite (node:sqlite — no Prisma engine,
 * no network, zero new deps; the load-bearing property is identical: a real
 * server-side DB write routed by a RUNTIME env var to a per-lane file). It honors
 * the §9.3 RUNTIME-ENV CONTRACT: `openDb()` reads `process.env.DATABASE_URL` at
 * REQUEST time (never a build-time-inlined constant), so one shared `next build` +
 * a per-lane DATABASE_URL at `next start` actually routes each lane to its own DB.
 *
 * Deliberately uses a SERVER-component page + a native form POST (no client
 * hydration needed), so the walk is robust: navigate -> submit -> the row is
 * written -> the page server-renders the new count from THIS lane's DB.
 *
 * fixtures.snapshotRestore.kind === 'db-file-copy' is the activation switch; the
 * runner's DbRestoreIsolation restores each lane to the seed before every mission.
 */
import type { GeneratedApp } from "./build-agent";
import type { GeneratedFile } from "./protocol";
import type { Mission, Action } from "../domain/types";
import { FIXTURES_FILENAME } from "./fixtures";

export const DB_STUB_PROMPT = "a counter whose count is stored in sqlite";

/** A build prompt the StubProvider routes to this app (no API key needed). */
export function isDbStubPrompt(prompt: string): boolean {
  return /\bsqlite\b/i.test(prompt);
}

export const DB_STUB_APP: GeneratedFile[] = [
  {
    path: "package.json",
    content: `{
  "name": "selfqa-generated-counter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.7",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/node": "^24",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}`,
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;`,
  },
  {
    path: "tsconfig.json",
    content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
  },
  {
    path: "postcss.config.mjs",
    content: `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;`,
  },
  {
    path: ".gitignore",
    content: `node_modules
.next
next-env.d.ts
*.db
*.db-wal
*.db-shm`,
  },
  {
    path: "src/app/globals.css",
    content: `@import "tailwindcss";`,
  },
  {
    path: "src/app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Counter",
  description: "A sqlite-backed counter generated by SelfQA",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  },
  {
    // RUNTIME-ENV CONTRACT: DATABASE_URL is read INSIDE openDb(), per call, never
    // at module scope — so it is NOT inlined by the shared production build.
    path: "src/lib/db.ts",
    content: `import { DatabaseSync } from "node:sqlite";

export function openDb(): DatabaseSync {
  const path = process.env.DATABASE_URL;
  if (!path) throw new Error("DATABASE_URL not set");
  return new DatabaseSync(path);
}`,
  },
  {
    // CLIENT component (no navigation): on mount it fetches the count, and the
    // button POSTs to /api/increment and updates state — the same client-fetch
    // interaction the walker already handles for the todo app. The server-side DB
    // write + per-lane DATABASE_URL routing happen in the route handlers below.
    path: "src/app/page.tsx",
    content: `"use client";

import { useEffect, useState } from "react";

export default function Page() {
  const [count, setCount] = useState<number | null>(null);

  useEffect(() => {
    fetch("/api/count")
      .then((r) => r.json())
      .then((d) => setCount(d.count))
      .catch(() => setCount(-1));
  }, []);

  async function increment() {
    const r = await fetch("/api/increment", { method: "POST" });
    const d = await r.json();
    setCount(d.count);
  }

  return (
    <main style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>Counter</h1>
      <p data-testid="count">{count === null ? "…" : count}</p>
      <button data-testid="increment" onClick={increment}>increment</button>
    </main>
  );
}`,
  },
  {
    path: "src/app/api/count/route.ts",
    content: `import { NextResponse } from "next/server";
import { openDb } from "@/lib/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(): Promise<Response> {
  const db = openDb();
  const row = db.prepare("SELECT COUNT(*) AS c FROM items").get() as { c: number };
  db.close();
  return NextResponse.json({ count: Number(row.c) });
}`,
  },
  {
    path: "src/app/api/increment/route.ts",
    content: `import { NextResponse } from "next/server";
import { openDb } from "@/lib/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(): Promise<Response> {
  const db = openDb();
  db.exec("INSERT INTO items (n) VALUES (1)");
  const row = db.prepare("SELECT COUNT(*) AS c FROM items").get() as { c: number };
  db.close();
  return NextResponse.json({ count: Number(row.c) });
}`,
  },
  {
    path: FIXTURES_FILENAME,
    content: `{
  "seedUsers": [],
  "mockKeys": {},
  "stubbedEmailOtp": false,
  "seedData": [{ "entity": "items", "id": "seed" }],
  "snapshotRestore": { "kind": "db-file-copy", "note": "per-lane DATABASE_URL -> own sqlite file; restore-to-seed before each mission" }
}`,
  },
];

export function dbStubApp(): GeneratedApp {
  return { prompt: DB_STUB_PROMPT, files: DB_STUB_APP };
}

/** The DDL the seed db and every lane share (must match src/lib/db usage). */
export const DB_STUB_SCHEMA = "CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, n INTEGER);";

/** The DB-writing mission the e2e walks in parallel: open -> increment -> count is 1. */
export function dbCounterMission(id: string): { mission: Mission; actions: Action[] } {
  return {
    mission: {
      id,
      name: "increment the counter",
      description: "submit the form once; the sqlite-backed count becomes 1",
      intendedSteps: ["open the counter", "click increment"],
      acceptanceCriteria: [
        { type: "deterministic", predicate: { kind: "text-equals", selector: "[data-testid=count]", expected: "1" }, nl: "count reads 1 after one increment" },
      ],
    },
    // the walker navigates to the lane's base url first; the sequence is just the
    // interaction (a leading relative navigate would be an invalid goto target).
    actions: [
      { kind: "click", target: { strategy: "data-testid", value: "increment" } },
    ],
  };
}
