/**
 * StubProvider — a deterministic, zero-cost drop-in for LLMProvider (SPEC §15).
 *
 * It lets the ENTIRE M1 loop (build → run → iframe → comment → edit → reload)
 * be verified end-to-end with no API key and no token spend. The real
 * AnthropicProvider implements the same interface, so swapping is one line.
 *
 * It routes on the `build-agent` / `edit-agent` / `spec-extractor` markers in
 * the system prompt (see codegen/prompts.ts).
 *
 * Server-intended.
 */
import type {
  LLMProvider,
  LLMCompletionRequest,
  LLMCompletionResult,
} from "./types";
import { serializeFileBlocks, type GeneratedFile } from "../codegen/protocol";

/** A tiny but real Next.js + Tailwind todo app — something with a form to comment on. */
const CANNED_TODO_APP: GeneratedFile[] = [
  {
    path: "package.json",
    content: `{
  "name": "selfqa-generated-todo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.7",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/node": "^24",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}`,
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;`,
  },
  {
    path: "tsconfig.json",
    content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
  },
  {
    path: "postcss.config.mjs",
    content: `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;`,
  },
  {
    path: ".gitignore",
    content: `node_modules
.next
next-env.d.ts`,
  },
  {
    path: "src/app/globals.css",
    content: `@import "tailwindcss";`,
  },
  {
    path: "src/app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo",
  description: "A tiny todo app generated by SelfQA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  },
  {
    path: "src/app/page.tsx",
    content: `"use client";

import { useState } from "react";

interface Todo {
  id: number;
  text: string;
}

export default function Home() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [text, setText] = useState("");
  const [nextId, setNextId] = useState(1);

  function addTodo(e: React.FormEvent) {
    e.preventDefault();
    const trimmed = text.trim();
    if (!trimmed) return;
    setTodos((prev) => [...prev, { id: nextId, text: trimmed }]);
    setNextId((n) => n + 1);
    setText("");
  }

  function removeTodo(id: number) {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <main className="mx-auto max-w-md p-8">
      <h1 className="mb-4 text-2xl font-bold" data-testid="title">
        Todo
      </h1>
      <form onSubmit={addTodo} className="mb-4 flex gap-2" data-testid="add-form">
        <input
          className="flex-1 rounded border px-3 py-2"
          placeholder="What needs doing?"
          value={text}
          onChange={(e) => setText(e.target.value)}
          data-testid="todo-input"
        />
        <button
          type="submit"
          className="rounded bg-black px-4 py-2 text-white"
          data-testid="add-button"
        >
          Add
        </button>
      </form>
      <p className="mb-2 text-sm text-gray-500" data-testid="count">
        {todos.length} item(s)
      </p>
      <ul data-testid="todo-list">
        {todos.map((t) => (
          <li
            key={t.id}
            className="flex items-center justify-between border-b py-2"
            data-testid="todo-item"
          >
            <span>{t.text}</span>
            <button
              className="text-sm text-red-600"
              onClick={() => removeTodo(t.id)}
              data-testid="remove-button"
            >
              Remove
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}`,
  },
];

export class StubProvider implements LLMProvider {
  readonly name = "stub";

  async complete(req: LLMCompletionRequest): Promise<LLMCompletionResult> {
    const system = req.system ?? "";

    if (system.includes("build-agent")) {
      return {
        text: serializeFileBlocks(CANNED_TODO_APP),
        stopReason: "end_turn",
      };
    }

    // edit-agent and spec-extractor canned responses arrive in Checkpoint D.
    throw new Error(
      `StubProvider: no canned response for this request (system marker not recognized)`,
    );
  }
}
