/**
 * StubProvider — a deterministic, zero-cost drop-in for LLMProvider (SPEC §15).
 *
 * It lets the ENTIRE M1 loop (build → run → iframe → comment → edit → reload)
 * be verified end-to-end with no API key and no token spend. The real
 * AnthropicProvider implements the same interface, so swapping is one line.
 *
 * It routes on the `build-agent` / `edit-agent` / `spec-extractor` markers in
 * the system prompt (see codegen/prompts.ts).
 *
 * Server-intended.
 */
import type {
  LLMProvider,
  LLMCompletionRequest,
  LLMCompletionResult,
} from "./types";
import { serializeFileBlocks, type GeneratedFile } from "../codegen/protocol";
import {
  STUB_COLD_MISSIONS,
  STUB_INFORMED_MISSIONS,
  STUB_COMPILED_SEQUENCES,
} from "./stub-missions";

/** A tiny but real Next.js + Tailwind todo app — something with a form to comment on. */
const CANNED_TODO_APP: GeneratedFile[] = [
  {
    path: "package.json",
    content: `{
  "name": "selfqa-generated-todo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.7",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "^4",
    "@types/node": "^24",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}`,
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;`,
  },
  {
    path: "tsconfig.json",
    content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
  },
  {
    path: "postcss.config.mjs",
    content: `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;`,
  },
  {
    path: ".gitignore",
    content: `node_modules
.next
next-env.d.ts`,
  },
  {
    path: "src/app/globals.css",
    content: `@import "tailwindcss";`,
  },
  {
    path: "src/app/layout.tsx",
    content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo",
  description: "A tiny todo app generated by SelfQA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  },
  {
    path: "src/app/page.tsx",
    content: `"use client";

import { useState } from "react";

interface Todo {
  id: number;
  text: string;
}

export default function Home() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [text, setText] = useState("");
  const [nextId, setNextId] = useState(1);
  const [error, setError] = useState("");

  function addTodo(e: React.FormEvent) {
    e.preventDefault();
    const trimmed = text.trim();
    if (!trimmed) {
      setError("Please enter a task");
      return;
    }
    setError("");
    setTodos((prev) => [...prev, { id: nextId, text: trimmed }]);
    setNextId((n) => n + 1);
    setText("");
  }

  function removeTodo(id: number) {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <main className="mx-auto max-w-md p-8">
      <h1 className="mb-4 text-2xl font-bold" data-testid="title">
        Todo
      </h1>
      <form onSubmit={addTodo} className="mb-4 flex gap-2" data-testid="add-form">
        <input
          className="flex-1 rounded border px-3 py-2"
          placeholder="What needs doing?"
          value={text}
          onChange={(e) => setText(e.target.value)}
          data-testid="todo-input"
        />
        <button
          type="submit"
          className="rounded bg-black px-4 py-2 text-white"
          data-testid="add-button"
        >
          Add
        </button>
      </form>
      {error ? (
        <p role="alert" data-testid="error" className="mb-2 text-sm text-red-600">
          {error}
        </p>
      ) : null}
      <p className="mb-2 text-sm text-gray-500" data-testid="count">
        {todos.length} item(s)
      </p>
      <ul data-testid="todo-list">
        {todos.map((t) => (
          <li
            key={t.id}
            className="flex items-center justify-between border-b py-2"
            data-testid="todo-item"
          >
            <span>{t.text}</span>
            <button
              className="text-sm text-red-600"
              onClick={() => removeTodo(t.id)}
              data-testid="remove-button"
            >
              Remove
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}`,
  },
  {
    path: "selfqa.fixtures.json",
    content: `{
  "seedUsers": [],
  "loginHook": { "kind": "none", "note": "client-state todo app: no auth" },
  "mockKeys": {},
  "stubbedEmailOtp": false,
  "seedData": [],
  "snapshotRestore": { "kind": "none", "note": "client-state app; DB restore lands with Prisma in M5" }
}`,
  },
];

export class StubProvider implements LLMProvider {
  readonly name = "stub";

  async complete(req: LLMCompletionRequest): Promise<LLMCompletionResult> {
    const system = req.system ?? "";
    // Route on the canonical role token on line 1 (collision-proof), never on
    // loose substrings that the prompt BODIES would trip (SPEC §6 spine work).
    const role =
      (system.split("\n", 1)[0].match(/^selfqa-role:\s*(\S+)/) ?? [])[1] ?? "";
    const userText = req.messages.map((m) => m.content).join("\n");

    if (role === "build-agent") {
      return {
        text: serializeFileBlocks(CANNED_TODO_APP),
        stopReason: "end_turn",
      };
    }

    if (role === "edit-agent") {
      // Tuple mode (M5-D): the prompt carries machine-readable assertions, so the
      // edit is a FUNCTION of the assertion (real consumption, not a fixed flip):
      // write each assertion's `expected` into the element bearing its testid.
      const asserts = [
        ...userText.matchAll(
          /SELFQA-ASSERT selector=(\S+) kind=(\S+) expected=("(?:[^"\\]|\\.)*")\nSELFQA-ASSERT-END/g,
        ),
      ];
      if (asserts.length > 0) {
        const pageMatch = userText.match(
          /--- src\/app\/page\.tsx ---\n([\s\S]*?)(?:\n--- [^\n]+ ---\n|\nSELFQA-FILES-END)/,
        );
        let page =
          pageMatch?.[1] ??
          CANNED_TODO_APP.find((f) => f.path === "src/app/page.tsx")?.content ??
          "";
        for (const m of asserts) {
          const tid = (m[1].match(/data-testid=([^\]]+)/) ?? [])[1];
          if (!tid) continue;
          const expected = JSON.parse(m[3]) as string;
          const esc = tid.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
          const re = new RegExp(
            '(data-testid="' + esc + '"[^>]*>)([\\s\\S]*?)(</)',
          );
          page = page.replace(re, `$1\n        ${expected}\n      $3`);
        }
        return {
          text: serializeFileBlocks([{ path: "src/app/page.tsx", content: page }]),
          stopReason: "end_turn",
        };
      }

      // Legacy fallback (no parsable assertion): unconditional title flip.
      const page = CANNED_TODO_APP.find((f) => f.path === "src/app/page.tsx");
      const edited = page
        ? page.content.replace("        Todo\n", "        Todo (edited by SelfQA)\n")
        : "";
      return {
        text: serializeFileBlocks(
          page ? [{ path: "src/app/page.tsx", content: edited }] : [],
        ),
        stopReason: "end_turn",
      };
    }

    if (role === "spec-extractor") {
      return {
        text: JSON.stringify({
          assertion: {
            type: "deterministic",
            predicate: {
              kind: "text-equals",
              selector: "[data-testid=title]",
              expected: "Todo (edited by SelfQA)",
            },
            nl: "the title should indicate it was edited",
          },
          clarifyingQuestion: null,
        }),
        stopReason: "end_turn",
      };
    }

    if (role === "mission-deriver") {
      const informed = userText.includes("MODE: informed");
      return {
        text: JSON.stringify(
          informed ? STUB_INFORMED_MISSIONS : STUB_COLD_MISSIONS,
        ),
        stopReason: "end_turn",
      };
    }

    if (role === "mission-compiler") {
      const m = userText.match(/Mission id:\s*(\S+)/);
      const id = m ? m[1] : "";
      return {
        text: JSON.stringify({ actions: STUB_COMPILED_SEQUENCES[id] ?? [] }),
        stopReason: "end_turn",
      };
    }

    if (role === "semantic-verdict") {
      // Deterministic stub: satisfied iff after differs from before; low confidence
      // iff the after snapshot carries the "UNSURE" marker.
      const m = userText.match(/SELFQA-SEM-ITEMS-START\n([\s\S]*?)\nSELFQA-SEM-ITEMS-END/);
      let items: { commentId: string; beforeSnapshot?: string; afterSnapshot?: string }[] = [];
      try {
        items = m ? JSON.parse(m[1]) : [];
      } catch {
        items = [];
      }
      const verdicts = items.map((it) => ({
        commentId: it.commentId,
        satisfied: (it.afterSnapshot ?? "") !== (it.beforeSnapshot ?? ""),
        confidence: String(it.afterSnapshot ?? "").includes("UNSURE") ? "low" : "high",
      }));
      return { text: JSON.stringify({ verdicts }), stopReason: "end_turn" };
    }

    throw new Error(
      "StubProvider: unrecognized role " +
        JSON.stringify(role) +
        " (expected a 'selfqa-role:' marker on line 1)",
    );
  }
}
